deployment:
  tasks:
    - export DEPLOYPATH=/home/theangel/public_html
    - /bin/cp -Ru * $DEPLOYPATH
    - /bin/chmod -R 755 $DEPLOYPATH
    - /bin/find $DEPLOYPATH -type d -exec chmod 755 {} \;
    - /bin/find $DEPLOYPATH -type f -exec chmod 644 {} \;