include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - .dart_tool/**
    - ios/**
    - android/**
    - lib/generated_plugin_registrant.dart
  
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # Performance
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    
    # Code Quality
    avoid_print: true
    avoid_unnecessary_containers: true
    avoid_empty_else: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    
    # Style
    prefer_single_quotes: true
    sort_child_properties_last: true
    use_key_in_widget_constructors: true
    
    # Error Prevention
    avoid_returning_null_for_void: true
    cancel_subscriptions: true
    close_sinks: true
