name: 🚀 Auto Deploy to cPanel via FTPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to cPanel with FTPS and cleanup
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        port: 21
        server-dir: ${{ secrets.FTP_REMOTE_DIR }}
        local-dir: ./
        max-ftp-threads: 10 # 👈 enables Thorttal 
        delete: true  # 👈 enables deletion of removed files
        exclude: |
          **/.git*
          **/.github*
          README.md
          .env
          *.env
          *.log
          node_modules/
          dist/
