name: 🚀 Auto Deploy to cPanel (FTPS, v5)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to cPanel with FTPS and deletion
      uses: SamKirkland/FTP-Deploy-Action@main
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        port: 21
        server-dir: ${{ secrets.FTP_REMOTE_DIR }}
        local-dir: ./
        delete: true                   # ✅ Only deletes files removed in repo
        max-ftp-threads: 10             # ✅ Upload multiple files in parallel
        exclude: |
          **/.git*
          **/.github*
          README.md
          .env
          *.env
          *.log
          node_modules/
          dist/
